/*
CAMPO FUTEBOL - CAM
COMERCIAL - COM
CONVENIO ETE CARIOBA - CON
ENTIDADE FILANTRÓPICA - ENT
HORTA - HOC
HORTA PARTICULAR - HOP
INDUSTRIAL - IND
IGREJAS E TEMPLOS RELIGIOSOS - ITR
PUBLICA ESTADUAL - PES
PUBLICA MUNICIPAL - PMU
PUBLICA NÃO MUNICIPAL - PNM
POÇOS ARTESIANO - POC
RESIDENCIAL - RES
RESIDENCIAL SOCIAL - SOC
TARIFA SOCIAL - TAR
TERRENO BALDIO - TER






$string_cat = "CAMPO FUTEBOL,COMERCIAL,CONVENIO ETE CARIOBA,ENTIDADE FILANTRÓPICA,HORTA,HORTA PARTICULAR,INDUSTRIAL,IGREJAS E TEMPLOS RELIGIOSOS,PUBLICA ESTADUAL,PUBLICA MUNICIPAL,PUBLICA NÃO MUNICIPAL,POÇOS ARTESIANO,RESIDENCIAL,RESIDENCIAL SOCIAL,TARIFA SOCIAL,TERRENO BALDIO";







*/
